### ISSUE TITLE
GodotSteam Module for 2.1.4 works in editor, breaks upon export

### ISSUE THREAD

**Issue by jeff-s-zhou** [Kermer/GodotSteam#15]
I've been testing basic functions for GodotSteam in a separate project, and they worked fine when used in the editor. However, upon exporting the project, I encountered the error below immediately upon opening the project.

For context, I'm running Windows, I used the pre-compiled 64-bit Godot executable downloaded from here, and I've included the steam_api64.dll in the directory of the Godot executable.

For my export, I've tried including the steam_api64.dll at the root level of the project's resources (at the same level as the engine.cfg) and made sure it was included in non-resources to be exported. That didn't work. I've also tried having it at the same level as the compiled export but external to it. I've received the same error either way. 

The fact that the Module works within the editor but not the exported project suggests I'm likely doing something wrong, but if not, then I can't think of what else to try other than compiling the Module myself. Please let me know if you have any ideas, and thank you for your time.

```
SCRIPT ERROR: GDScript::load_byte_code: Compile Error: Identifier not found: Steam
          At: res://Main.gdc:12
ERROR: GDScript::load_byte_code: Method/Function Failed, returning: ERR_COMPILATION_FAILED
   At: modules\gdscript\gd_script.cpp:690
ERROR: ResourceFormatLoaderGDScript::load: Condition ' err != OK ' is true. returned: RES()
   At: modules\gdscript\gd_script.cpp:1757
ERROR: Failed loading resource: res://Main.gd
   At: core\io\resource_loader.cpp:210
ERROR: Can't load dependency: res://Main.gd
   At: core\io\resource_format_binary.cpp:717
ERROR: ResourceFormatLoader::load: Condition ' err != OK ' is true. returned: RES()
   At: core\io\resource_loader.cpp:137
ERROR: Failed loading resource: res://Main.tscn
   At: core\io\resource_loader.cpp:210
ERROR: Failed loading scene: res://Main.tscn
   At: main\main.cpp:1409
ERROR: SpatialSoundServerSW::free: Attempt to free invalid ID
   At: servers\spatial_sound\spatial_sound_server_sw.cpp:598
ERROR: SpatialSound2DServerSW::free: Attempt to free invalid ID
   At: servers\spatial_sound_2d\spatial_sound_2d_server_sw.cpp:595
WARNING: ObjectDB::cleanup: ObjectDB Instances still exist!
     At: core\object.cpp:1845

```

**Comment by Kermer** [comment]
It looks like you're trying to use an export template which isn't compiled with this GodotSteam module (_Identifier not found: Steam_).
For testing purposes you can select your editor's executable as export template (this is **almost** the same as using debug template)
![image](https://user-images.githubusercontent.com/10342043/35770226-a2fc372e-0917-11e8-80ee-595b6738e2ba.png)

**You should also check the "[Creating Windows export templates](http://docs.godotengine.org/en/2.1/development/compiling/compiling_for_windows.html#creating-windows-export-templates)" documentation.**

**Comment by Kermer** [comment]
And if I remember correctly - you might need a "**steam_appid.txt**", containing steam id of your app, next to your executable.
You probably should be able to impersonate Spacewar (AppID: 480) for development purposes.

**Comment by jeff-s-zhou** [comment]
You're right, it's the template. In fact, I actually meant to raise the issue on the other GodotSteam repo. Thank you nonetheless haha.
