### ISSUE TITLE
Compilation Errors with Godot 2.1 

### ISSUE THREAD

**Issue by MatteoJoliveau** [Kermer/GodotSteam#8]
Hi there
I downloaded the latest version of Steamworks SDK (137) and Godot 2.1 source code. I followed closely all the steps described in the module doc but when I run scons to compile the engine, this is the output I get:

> In file included from modules/godotsteam/godotsteam.cpp:2:0:
> modules/godotsteam/godotsteam.h:53:35: warning: converting to non-pointer type 'int' from NULL [->Wconversion-null]
>  void updateFriendList(int filter=NULL); // default = last used filter
>                                   ^~~~
> In file included from /usr/include/alloca.h:24:0,
>                 from platform/x11/platform_config.h:30,
>                 from core/safe_refcount.h:35,
>                 from core/os/memory.h:33,
>                 from core/list.h:32,
>                 from core/object.h:32,
>                 from modules/godotsteam/godotsteam.h:7,
>                 from modules/godotsteam/godotsteam.cpp:2:
> modules/godotsteam/godotsteam.h: In member function 'virtual void >Steam::CCallbackInternal__avatar_loaded::Run(void*)':
> modules/godotsteam/godotsteam.h:59:17: warning: offsetof within non-standard-layout type 'Steam' >is undefined [-Winvalid-offsetof]
>  STEAM_CALLBACK(Steam, _avatar_loaded, AvatarImageLoaded_t );
> 
> modules/godotsteam/sdk/public/steam/steam_api_internal.h:184:58: note: in expansion of macro >'_STEAM_CALLBACK_3'
> # define _STEAM_CALLBACK_HELPER( _1, _2, SELECTED, ... )  _STEAM_CALLBACK_##SELECTED
> 
> ```
>                                                      ^~~~~~~~~~~~~~~~
> ```
> 
> modules/godotsteam/sdk/public/steam/steam_api.h:218:2: note: in expansion of macro >'_STEAM_CALLBACK_SELECT'
>  _STEAM_CALLBACK_SELECT( ( __VA_ARGS__, 4, 3 ), ( /*_/, thisclass, func, **VA_ARGS** ) )
>  ^~~~~~~~~~~~~~~~~~~~~~
> modules/godotsteam/godotsteam.h:59:2: note: in expansion of macro 'STEAM_CALLBACK'
>  STEAM_CALLBACK(Steam, _avatar_loaded, AvatarImageLoaded_t );
>  ^~~~~~~~~~~~~~
> modules/godotsteam/godotsteam.cpp: In member function 'String Steam::get_userdata_path()':
> modules/godotsteam/godotsteam.cpp:57:50: error: uninitialized const in 'new' of 'const char'
>  const char *pchBuffer = new const char[cubBuffer];
>                                                  ^
> modules/godotsteam/godotsteam.cpp:58:7: warning: unused variable 'error' [-Wunused-variable]>
>  bool error = SteamUser()->GetUserDataFolder( (char_)pchBuffer, cubBuffer );
>      ^~~~~
> modules/godotsteam/godotsteam.cpp: In member function 'String Steam::get_username(int)':
> modules/godotsteam/godotsteam.cpp:74:54: warning: comparison between signed and unsigned >integer expressions [-Wsign-compare]
> if ( SteamUser() != NULL && (steamId < 0 || steamId == SteamUser()->GetSteamID().GetAccountID()) )
>                                             >~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> scons: **\* [modules/godotsteam/godotsteam.x11.tools.64.o] Error 1
> scons: building terminated because of errors.

What am I doing wrong?

**Comment by Kermer** [comment]
Actually `updateFriendList()` and `updateGroupList()` do not exist anymore (changed a lot since first version), so you could try commenting both of them in `godotsteam.h` and let me know if compiling succeeded.

Got to confess, that I haven't compiled this for over 3 months already.
I recently formatted my PC, so I don't have all the tools to test this myself right now.

Also: which compiler do you use?

**Comment by MatteoJoliveau** [comment]
Commented that out, still getting errors

> In file included from /usr/include/alloca.h:24:0,
>                 from platform/x11/platform_config.h:30,
>                 from core/safe_refcount.h:35,
>                 from core/os/memory.h:33,
>                 from core/list.h:32,
>                 from core/object.h:32,
>                 from modules/godotsteam/godotsteam.h:7,
>                 from modules/godotsteam/godotsteam.cpp:2:
> modules/godotsteam/godotsteam.h: In member function 'virtual void >Steam::CCallbackInternal__avatar_loaded::Run(void*)':
> modules/godotsteam/godotsteam.h:59:17: warning: offsetof within non-standard-layout type 'Steam' >is undefined [-Winvalid-offsetof]
> STEAM_CALLBACK(Steam, _avatar_loaded, AvatarImageLoaded_t );
> 
> modules/godotsteam/sdk/public/steam/steam_api_internal.h:184:58: note: in expansion of macro >'_STEAM_CALLBACK_3'
> #define _STEAM_CALLBACK_HELPER( _1, _2, SELECTED, ... )  _STEAM_CALLBACK_##SELECTED
>                                                          ^~~~~~~~~~~~~~~~
> modules/godotsteam/sdk/public/steam/steam_api.h:218:2: note: in expansion of macro >'_STEAM_CALLBACK_SELECT'
>  _STEAM_CALLBACK_SELECT( ( __VA_ARGS__, 4, 3 ), ( /*_/, thisclass, func, **VA_ARGS** ) )
>  ^~~~~~~~~~~~~~~~~~~~~~
> modules/godotsteam/godotsteam.h:59:2: note: in expansion of macro 'STEAM_CALLBACK'
>  STEAM_CALLBACK(Steam, _avatar_loaded, AvatarImageLoaded_t );
>  ^~~~~~~~~~~~~~
> modules/godotsteam/godotsteam.cpp: In member function 'String Steam::get_userdata_path()':
> modules/godotsteam/godotsteam.cpp:57:50: error: uninitialized const in 'new' of 'const char'
> const char *pchBuffer = new const char[cubBuffer];
>                                                 ^
> modules/godotsteam/godotsteam.cpp:58:7: warning: unused variable 'error' [-Wunused-variable]
>  bool error = SteamUser()->GetUserDataFolder( (char_)pchBuffer, cubBuffer );
>      ^~~~~
> modules/godotsteam/godotsteam.cpp: In member function 'String Steam::get_username(int)':
> modules/godotsteam/godotsteam.cpp:74:54: warning: comparison between signed and unsigned >integer expressions [-Wsign-compare]
>  if ( SteamUser() != NULL && (steamId < 0 || steamId == SteamUser()->GetSteamID().GetAccountID()) )
>                                              >~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> scons: **\* [modules/godotsteam/godotsteam.x11.tools.64.o] Error 1
> scons: building terminated because of errors.

Thanks for answering so quick btw

**Comment by Kermer** [comment]
I'll try to setup the tools and try to compile myself in next days. Note that **I'm working on Windows**, so I can't assure you that it will work the same for both of us.

If I read this right... The only error left now is 
`godotsteam.cpp:57:50: error: uninitialized const in 'new' of 'const char'`
rest is just warnings and notes, but something else might show up once you deal with this one :P

**Comment by MatteoJoliveau** [comment]
Thank you, I think it is not really something related to the platform, but everything could be. I tried to compile it under Linux, but I can try as well on Windows tomorrow. I will let you know, and wait for your feedback as well

**Comment by Kermer** [comment]
It works fine on win7 x64, with MS VS Community 2015 (x86). Even without the recent fixes.

Changed
`const char *pchBuffer = new const char[cubBuffer];`
to
`char *pchBuffer = new char[cubBuffer];`
so please test it on Linux now :)

Please test with **leaderboards branch**, not master

**Comment by MatteoJoliveau** [comment]
Good, changin the line you highlighted fixed the issue, I'm done compiling right now. I used the master branch however, no problems.
On the other hand, when I try to run the Godot executable, it throws an error about not finding the libsteam library. I tryed both bin/ and modules/godotsteam/ as locations for the library, same error. Where should I put it?

**Comment by Kermer** [comment]
Check `README.md`

> Linux 32
> 
> ./linux32/libsteam_api.so
> ./godot_binary
> 
> Linux 64
> 
> ./linux64/libsteam_api.so
> ./godot_binary

**Comment by MatteoJoliveau** [comment]
Ok, didn't understand that I needed to put the entire linux32 or 64 directory, now it's working fine.
Thanks very much for your help!
