### ISSUE TITLE
join_requested Signal?

### ISSUE THREAD

**Issue by Gramps** [Kermer/GodotSteam#9]
This isn't quite an issue with the module, but I have no idea how you are supposed to use the join_requested signal in Godot itself.  It does not come up under the Steam class but does show in the help listing.

How are you using it in Godot?

**Comment by Kermer** [comment]
It's SteamAPI. I now see that this signal name can be quite misleading.
It's emitted when one of your friends invites you to join his game while you're already in-game.
Mind that networking and social stuff isn't fully complete yet.

It works something like:
1. Your friend invites you via Steam overlay, invite_friend(), etc.
2. SteamUC object emits `join_requested` signal containing that friend's SteamID and `connect_string` which is a hint how to join that game (for example IP, it's 2nd argument of invite_friend() function).

Something like this probably would work:

``` js
var server_ip = ""
func _ready():
    SteamUC.connect("join_requested",self,"_game_invite_received")

func _game_invite_received( from_id, connect_string ):
    server_ip = connect_string
    var friend_name = Steam.get_username( from_id )
    show_friend_join_popup(friend_name)
```

**Comment by Gramps** [comment]
Hmm, makes sense.  I've been tinkering with getting Godot's networking from 2.2 and Steamworks API to play nice.  Noticed you had this signal in your module when I was pulling your last update and merging it into my fork (also adding in Remote Storage functions), but couldn't figure out how the signal was supposed to work.

With this in mind I'll mess around with it more as well as try to add in more networking stuff from iSteamMatchmaking.

Cheers!
